# -*- coding: utf-8 -*-
"""LR_2_task_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcXoter_xWoyQeOwW0ydFl_O-qAWOIlJ
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from io import BytesIO

iris = load_iris()
X, y = iris.data, iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

clf = RidgeClassifier(tol=1e-2, solver="sag")
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print('Accuracy:', np.round(metrics.accuracy_score(y_test, y_pred), 4))
print('Precision:', np.round(metrics.precision_score(y_test, y_pred, average='weighted'), 4))
print('Recall:', np.round(metrics.recall_score(y_test, y_pred, average='weighted'), 4))
print('F1 Score:', np.round(metrics.f1_score(y_test, y_pred, average='weighted'), 4))
print('Cohen Kappa Score:', np.round(metrics.cohen_kappa_score(y_test, y_pred), 4))
print('Matthews Corrcoef:', np.round(metrics.matthews_corrcoef(y_test, y_pred), 4))

print('\n\t\tClassification Report:\n', metrics.classification_report(y_test, y_pred))

conf_mat = confusion_matrix(y_test, y_pred)

sns.set()
plt.figure(figsize=(6, 5))
sns.heatmap(conf_mat, annot=True, fmt='d', cmap='Blues', square=True, cbar=False)
plt.xlabel('Predicted label')
plt.ylabel('True label')
plt.title("Confusion Matrix - Ridge Classifier")
plt.tight_layout()
plt.savefig("Confusion.jpg")