# -*- coding: utf-8 -*-
"""Л.р.2(завдання 1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1larbR2aJJ4G0LygVDiFYsoA3QKDQEiOl
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsOneClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, accuracy_score

from google.colab import files
uploaded = files.upload()
input_file = 'adult.data'

X = []
y = []
count_class1 = 0
count_class2 = 0
max_datapoints = 25000

# Читання і фільтрація даних
with open(input_file, 'r') as f:
    for line in f.readlines():
        if count_class1 >= max_datapoints and count_class2 >= max_datapoints:
            break
        if '?' in line:
            continue
        data = line.strip().split(', ')
        if data[-1] == '<=50K' and count_class1 < max_datapoints:
            X.append(data[:-1])
            y.append(0)
            count_class1 += 1
        elif data[-1] == '>50K' and count_class2 < max_datapoints:
            X.append(data[:-1])
            y.append(1)
            count_class2 += 1

# Перетворення в масив NumPy
X = np.array(X)
y = np.array(y)

# Кодування категоріальних ознак
label_encoders = []
X_encoded = np.empty(X.shape)

for i in range(X.shape[1]):
    if X[0, i].isdigit():
        X_encoded[:, i] = X[:, i]
    else:
        le = preprocessing.LabelEncoder()
        X_encoded[:, i] = le.fit_transform(X[:, i])
        label_encoders.append(le)

X_encoded = X_encoded.astype(int)

# Поділ на тренувальні та тестові дані
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=5)

# Навчання SVM-класифікатора
classifier = OneVsOneClassifier(LinearSVC(random_state=0, max_iter=10000))
classifier.fit(X_train, y_train)

# Прогнозування
y_pred = classifier.predict(X_test)

# Оцінка моделі
print("\nОцінка класифікатора:")
print("Accuracy: {:.2f}%".format(accuracy_score(y_test, y_pred)*100))

f1 = cross_val_score(classifier, X_encoded, y, scoring='f1_weighted', cv=3)
print("F1 score: {:.2f}%".format(f1.mean()*100))

print("\nДокладний звіт:\n")
print(classification_report(y_test, y_pred, target_names=["<=50K", ">50K"]))

# Тестова точка
input_data = ['37', 'Private', '215646', 'HS-grad', '9', 'Never-married',
              'Handlers-cleaners', 'Not-in-family', 'White', 'Male', '0',
              '0', '40', 'United-States']

# Кодування тестової точки
input_data_encoded = []
label_index = 0

for i, item in enumerate(input_data):
    if item.isdigit():
        input_data_encoded.append(int(item))
    else:
        le = label_encoders[label_index]
        input_data_encoded.append(int(le.transform([item])[0]))
        label_index += 1

input_data_encoded = np.array(input_data_encoded).reshape(1, -1)

predicted_class = classifier.predict(input_data_encoded)[0]
print("Прогноз для тестової точки:", ">50K" if predicted_class == 1 else "<=50K")